codecov:
  branch: master

coverage:
  precision: 2
  round: down
  range: "70...100"

  ignore:
    - "Tests/*"

  notify:
    slack:
      default:
        url: "secret:NnVfkTAF7NSxRk1AAGU13WKLgty/kCIY3mpKlUy5NpqlYdEiYxz/VbEelmj5aIm2I6roJJZY4KbICMO9GlbkwG+i19hJBKF1oo9Z3ZR3M0ICwJ9hUrPVZ4cg1pCKKUjZ4mi/nELOwxdYazhNCgNGx1huu0QTHB5059rYmEr5xWw="
        attachments: "sunburst, diff"

  fixes:
    - "Sources/::"

comment:
  layout: "header, sunburst, diff, changes, uncovered, suggestions"
